// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddToCartButton: typeof import('./components/AddToCartButton.vue')['default']
    CartItem: typeof import('./components/CartItem.vue')['default']
    IconCart: typeof import('./components/icons/IconCart.vue')['default']
    IconClose: typeof import('./components/icons/IconClose.vue')['default']
    IconEmptyStar: typeof import('./components/icons/IconEmptyStar.vue')['default']
    IconFilledStar: typeof import('./components/icons/IconFilledStar.vue')['default']
    IconSearch: typeof import('./components/icons/IconSearch.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    ProductList: typeof import('./components/ProductList.vue')['default']
    Rating: typeof import('./components/Rating.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    TopBar: typeof import('./components/TopBar.vue')['default']
  }
}
